sudo: required
services:
  - docker

env:
  - NODE_VERSION=8-jessie
  - NODE_VERSION=10-jessie
  - NPM_TARGET=test
  - NPM_TARGET=lint
  - NPM_TARGET=coverage



before_install:
  - docker pull node:8-onbuild

install:
  - docker build -t probot-hello .

script:
  - docker login -u="{$DOCKER_USERNAME}" -p="{$DOCKER_PASSWD}"
  - docker build -t node:$NODE_VERSION --build-arg NODE_IMAGE="node:${NODE_VERSION}" .
  - docker images
  - docker tag node:$NODE_VERSION $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD)
  - docker push $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD)

  
